In [4]:
from nwb_utils import NWBUtils
from optogenetics_utils import create_opto_data_frame, find_unique_combinations

In [2]:
nwb_path="/root/capsule/data/optogenetics_nwb/789197_2025-08-05_10-49-42.nwb"

nwb_data=NWBUtils.read_behavior_nwb(nwb_full_path=nwb_path)

Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-08-05_10-49-42.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-08-05_10-49-42.nwb

In [3]:
data_frame=create_opto_data_frame(nwb_data)

In [5]:
find_unique_combinations(data_frame,['animal_response','bait_right'])

   animal_response  bait_right
0              0.0       False
1              2.0       False
2              0.0        True
3              1.0        True
4              1.0       False
5              2.0        True

In [4]:
data_frame.columns

Index(['start_time', 'stop_time', 'animal_response', 'rewarded_historyL',
       'rewarded_historyR', 'delay_start_time', 'goCue_start_time',
       'reward_outcome_time', 'bait_left', 'bait_right',
       'base_reward_probability_sum', 'reward_probabilityL',
       'reward_probabilityR', 'reward_random_number_left',
       'reward_random_number_right', 'left_valve_open_time',
       'right_valve_open_time', 'block_beta', 'block_min', 'block_max',
       'min_reward_each_block', 'delay_beta', 'delay_min', 'delay_max',
       'delay_duration', 'ITI_beta', 'ITI_min', 'ITI_max', 'ITI_duration',
       'response_duration', 'reward_consumption_duration', 'reward_delay',
       'auto_waterL', 'auto_waterR', 'laser_on_trial', 'laser_wavelength',
       'laser_location', 'laser_1_power', 'laser_2_power',
       'laser_on_probability', 'laser_duration', 'laser_condition',
       'laser_condition_probability', 'laser_start', 'laser_start_offset',
       'laser_end', 'laser_end_offset', 'laser_protocol', 'laser_frequency',
       'laser_rampingdown', 'laser_pulse_duration', 'session_wide_control',
       'fraction_of_session', 'session_start_with', 'session_alternation',
       'minimum_opto_interval', 'auto_train_engaged',
       'auto_train_curriculum_name', 'auto_train_curriculum_version',
       'auto_train_curriculum_schema_version', 'auto_train_stage',
       'auto_train_stage_overridden', 'lickspout_position_x',
       'lickspout_position_z', 'lickspout_position_y', 'reward_size_left',
       'reward_size_right', 'session', 'box', 'session_end_time',
       'session_run_time_in_min', 'water_in_session_foraging',
       'water_in_session_manual', 'water_in_session_total',
       'water_after_session', 'water_day_total', 'base_weight',
       'target_weight', 'target_weight_ratio', 'weight_after',
       'foraging_efficiency', 'foraging_efficiency_with_actual_random_seed',
       'laser_1_calibration_power', 'laser_2_calibration_power',
       'laser_1_target_areas', 'laser_2_target_areas', 'commit_ID', 'repo_url',
       'current_branch'],
      dtype='object')

In [9]:
nwb_data.scratch['metadata']

metadata hdmf.common.table.DynamicTable at 0x139860938781168
Fields:
  colnames: ['box' 'session_end_time' 'session_run_time_in_min'
 'water_in_session_foraging' 'water_in_session_manual'
 'water_in_session_total' 'water_after_session' 'water_day_total'
 'base_weight' 'target_weight' 'target_weight_ratio' 'weight_after'
 'foraging_efficiency' 'foraging_efficiency_with_actual_random_seed'
 'laser_1_calibration_power' 'laser_2_calibration_power'
 'laser_1_target_areas' 'laser_2_target_areas' 'commit_ID' 'repo_url'
 'current_branch']
  columns: (
    box <class 'hdmf.common.table.VectorData'>,
    session_end_time <class 'hdmf.common.table.VectorData'>,
    session_run_time_in_min <class 'hdmf.common.table.VectorData'>,
    water_in_session_foraging <class 'hdmf.common.table.VectorData'>,
    water_in_session_manual <class 'hdmf.common.table.VectorData'>,
    water_in_session_total <class 'hdmf.common.table.VectorData'>,
    water_after_session <class 'hdmf.common.table.VectorData'>,
    water_day_total <class 'hdmf.common.table.VectorData'>,
    base_weight <class 'hdmf.common.table.VectorData'>,
    target_weight <class 'hdmf.common.table.VectorData'>,
    target_weight_ratio <class 'hdmf.common.table.VectorData'>,
    weight_after <class 'hdmf.common.table.VectorData'>,
    foraging_efficiency <class 'hdmf.common.table.VectorData'>,
    foraging_efficiency_with_actual_random_seed <class 'hdmf.common.table.VectorData'>,
    laser_1_calibration_power <class 'hdmf.common.table.VectorData'>,
    laser_2_calibration_power <class 'hdmf.common.table.VectorData'>,
    laser_1_target_areas <class 'hdmf.common.table.VectorData'>,
    laser_2_target_areas <class 'hdmf.common.table.VectorData'>,
    commit_ID <class 'hdmf.common.table.VectorData'>,
    repo_url <class 'hdmf.common.table.VectorData'>,
    current_branch <class 'hdmf.common.table.VectorData'>
  )
  description: Some important session-wise meta data
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

In [13]:
nwb_data.session_id

'789197_2025-08-05_10-49-42.json'