In [1]:
from nwb_utils import NWBUtils
from optogenetics_utils import create_opto_data_frame, find_unique_combinations,find_unique_stimulation,create_opto_data_frame_combined,load_opto_data_frame,find_unique_values_by_conditions

In [ ]:
combined_dataframe=create_opto_data_frame_combined(save_path='/root/capsule/results/combined_opto_data_frame.csv')

In [2]:
combined_dataframe=load_opto_data_frame()

In [3]:
find_unique_stimulation(combined_dataframe)

,laser_on_trial,laser_wavelength,laser_location,laser_1_power,laser_2_power,laser_on_probability,laser_duration,laser_start,laser_start_offset,laser_end,laser_end_offset,laser_protocol,laser_frequency,laser_rampingdown,laser_pulse_duration,session_wide_control,fraction_of_session,session_start_with,session_alternation,n_trials
0,1,473.0,Both,1.15,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,177
1,1,473.0,Both,1.34,1.35,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,141
2,1,473.0,Both,1.4,1.48,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,103
3,1,473.0,Both,1.26,1.21,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,88
4,1,473.0,Both,1.4,1.48,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,83
5,1,473.0,Both,1.4,1.48,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,81
6,1,473.0,Both,1.4,1.48,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,80
7,1,473.0,Both,1.12,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,70
8,1,473.0,Both,1.43,1.4,0.12,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,1.0,0.002,off,0.5,on,on,34
9,1,473.0,Both,1.36,1.4,0.12,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,31
10,1,473.0,Both,1.4,1.48,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,31
11,1,473.0,Both,1.34,1.35,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,24
12,1,473.0,Both,2.27,2.38,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,24
13,1,473.0,Both,1.15,1.19,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,21
14,1,473.0,Both,1.15,1.19,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,19
15,1,473.0,Both,2.27,2.38,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,19
16,1,473.0,Both,1.15,1.19,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,18
17,1,473.0,Both,1.2,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,17
18,1,473.0,Both,2.27,2.38,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,16

In [4]:
find_unique_stimulation(combined_dataframe,columns=[
        'laser_on_trial', 'laser_wavelength', 'laser_location',   'laser_duration', 'laser_start',
        'laser_start_offset', 'laser_end', 'laser_end_offset', 'laser_protocol',
        'laser_frequency',  'laser_pulse_duration',
        'session_wide_control', 'fraction_of_session', 'session_start_with',
        'session_alternation'
    ])

,laser_on_trial,laser_wavelength,laser_location,laser_duration,laser_start,laser_start_offset,laser_end,laser_end_offset,laser_protocol,laser_frequency,laser_pulse_duration,session_wide_control,fraction_of_session,session_start_with,session_alternation,n_trials
0,1,473.0,Both,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.002,off,0.5,on,on,834
1,1,473.0,Both,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.002,off,0.5,on,on,123
2,1,473.0,Both,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.002,off,0.5,on,on,120

In [7]:
conds = {"laser_start": "Go cue", "laser_end": "Trial start"}
unique_vals = find_unique_values_by_conditions(combined_dataframe, conds, output_column="session")
print(unique_vals)

['788198_2025-06-24_12-06-50', '788198_2025-07-07_13-46-12', '788198_2025-07-10_08-56-13', '788198_2025-07-11_10-20-29', '788198_2025-07-22_13-28-53', '788198_2025-07-31_12-43-14', '788198_2025-08-07_14-05-27']

In [ ]:
nwb_path="/root/capsule/data/optogenetics_nwb/789197_2025-08-05_10-49-42.nwb"

nwb_data=NWBUtils.read_behavior_nwb(nwb_full_path=nwb_path)

In [ ]:
data_frame

In [ ]:
find_unique_stimulation(data_frame)

In [ ]:
data_frame.columns

In [ ]:
nwb_data.scratch['metadata']

In [ ]:
nwb_data.session_id